name: Deploy MinIO

on:
  push:
    branches:
      - main  # Trigger this workflow when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: self-hosted  # You can change this to a specific runner type if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building images if necessary

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx

      - name: Run MinIO server container
        run: |
          docker run -d -p 9000:9000 -p 9090:9090 \
            -e "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" \
            -e "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" \
            -e "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" \
            -e "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" \
            -e "MINIO_HOST=0.0.0.0" \
            -e "MINIO_PORT=9000" \
            -e "MINIO_CONSOLE_PORT=9090" \
            --name minio-server \
            minio/minio server /data --address 0.0.0.0:9000 --console-address 0.0.0.0:9090
          
      - name: Check if MinIO is healthy
        run: |
          curl -f http://localhost:9000/minio/health/live || exit 1  # Check if MinIO is running fine

